CRUD-Alumnos/Controllers/AlumnoController.cs
using CRUD_Alumnos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD_Alumnos.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        public ActionResult Index()
        {
            try
            {
                /*Cuando usamos más de una tabla tenemos que usar transaciones */
                using (var db = new Model())
                {
                    //List<Alumno> lista = db.Alumno.Where(a => a.Edad > 18).ToList();  
                    return View(db.Alumno.ToList());
                    //return View(lista);

                }

            }
            catch (Exception)
            {
                throw;
            }

            //db.Alumno.ToList();
            //List<Alumno> lista = db.Alumno.Where(a => a.Edad > 18).ToList();  
            // db.Alumno.Where(a => a.Edad > 18).ToList();
            //return View(lista);
        }

        [HttpGet]
        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        //Esto crea un token que verifica que el formulario que se envia es el correcto
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(Alumno a)
        {
            //Aca consulto sobre si, el modelo que entra es valido y sino es valido 
            //me retorna la vista y los errores que hay en ValitionSummary
            if (!ModelState.IsValid)
                return View();

            try
            {
                //Es importante utilizar el using para que abra la conexion
                //y a la vez que la cierre para que no quede una conexion abierta
                //y no este consumiendo mucho recursos
                using (Model db = new Model())
                {
                    a.FechaRegistro = DateTime.Now;

                    //Agrego un alumno
                    db.Alumno.Add(a);
                    //Guardo los cambios
                    db.SaveChanges();

                    //return View();
                    //Cuando esta todo bien utilizo un redirect para direccionarlo 
                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al agregar un Alumno", ex.Message);

                return View();
            }
        }


        public ActionResult Agregar2()
        {
            return View();
        }

        public ActionResult ListaCiudades()
        {
            using (var db = new Model())
            {
                //Retorno a vista con todas las ciudad
                return PartialView(db.Ciudad.ToList());
            }
        }


        public ActionResult Editar(int id)
        {
            try
            {
                using (var db = new Model())
                {
                    //Alumno alumnos = db.Alumno.Where(a => a.Id == id).FirstOrDefault();
                    Alumno alum = db.Alumno.Find(id);
                    return View(alum);

                }
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Alumno a)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();
                using (var db = new Model())
                {
                    Alumno al = db.Alumno.Find(a.Id);
                    al.Nombres = a.Nombres;
                    al.Apellidos = a.Apellidos;
                    al.Edad = a.Edad;
                    al.Sexo = a.Sexo;

                    //Para guardar los cambios
                    db.SaveChanges();
                    //Una vez guardado lo redirecciono a index
                    return RedirectToAction("Index");

                }
            }
            catch (Exception)
            {
                throw;
            }
        }


        public ActionResult DetallesAlumno(int id)
        {
            try
            {
                using (var db = new Model())
                {
                    //Alumno alumnos = db.Alumno.Where(a => a.Id == id).FirstOrDefault();
                    Alumno alum = db.Alumno.Find(id);
                    return View(alum);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }


        public ActionResult Eliminar(int id )
        {
            try
            {
                using (var db = new Model())
                {
                    //Alumno alumnos = db.Alumno.Where(a => a.Id == id).FirstOrDefault();
                    //Primero lo buscamos y si lo encontramos lo eliminamos y luego guardamos
                    Alumno alum = db.Alumno.Find(id);
                    db.Alumno.Remove(alum);
                    db.SaveChanges();
                    
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                throw;
            }
        }


        public static string NombreDeLaCiudad(int idCiudad)
        {
            using (var db = new Model())
            {
                //Le indico que busque en la tabla ciudad el codCiudad que le paso
                //por parametro y que me traiga el nombre de la ciudad
                return db.Ciudad.Find(idCiudad).Nombre;
            }
        }


    }
}

CRUD-Alumnos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>

    @*
     Con los @Styles.Render() cargo los estilos     
    *@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    @* Seria le paso el titulo el texto, nombre de la accion, y el nombre del controlador  *@
                    <li>@Html.ActionLink("Alumnos", "Index", "Alumno")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @*
            El @RenderBody() es donde va estar todo el contenido de la pagina
        *@
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @RenderSection("scripts", required: false)


    @*
    El @RenderSection() es para renderizar una sesion de script
    *@
</body>
</html>